# Build vanadium-builder and vanadium-native-builder and push the
# resulting docker images to GitHub Packages.

name: Vanadium Builder

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-packages.yml
      - native.Dockerfile
      - Dockerfile

jobs:
  build:
    name: Build and push vanadium-builder image
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Clone
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.CI_BOT_PAT }}

    - name: Build and push vanadium-builder to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        dockerfile: Dockerfile
        repository: ledgerhq/vanadium-builder
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        tag_with_sha: true
        tags: latest

    - name: Build and push vanadium-native-builder to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        dockerfile: native.Dockerfile
        repository: ledgerhq/vanadium-native-builder
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        tag_with_sha: true
        tags: latest
